[package]
name = "conchord"
version = "0.2.0"
entrypoint = "lib.typ"
authors = ["sitandr"]
license = "MIT"
description = "Easily write lyrics with chords, generate chord diagrams by chord names and draw tabs."
exclude = ["examples"]
repository = "https://github.com/sitandr/conchord"
compiler = "0.11.0"
keywords = ["music", "chord", "chords", "tab", "tablature", "tabulature", "guitar", "song"]
categories = ["visualization", "components"]
disciplines = ["music"]
